# Form implementation generated from reading ui file 'listwidgetapp.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog, QInputDialog, QLineEdit, QMessageBox
from DB import db


class Ui_Dialog(QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtWidgets.QListWidget(parent=Dialog)
        # 开启自动排序
        self.listWidget.setSortingEnabled(True)
        self.listWidget.setStyleSheet("background:rgb(166, 255, 196);\n"
                                      "font: 700 12pt \"Microsoft YaHei UI\";")
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout.addWidget(self.listWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_add = QtWidgets.QPushButton(parent=Dialog)

        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_add.clicked.connect(self.add_item)
        self.verticalLayout.addWidget(self.pushButton_add)
        self.pushButton_edit = QtWidgets.QPushButton(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.pushButton_edit.setFont(font)
        self.pushButton_edit.setObjectName("pushButton_edit")
        self.pushButton_edit.clicked.connect(self.edit_item)
        self.verticalLayout.addWidget(self.pushButton_edit)
        self.pushButton_delete = QtWidgets.QPushButton(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.pushButton_delete.clicked.connect(self.delete_item)
        self.verticalLayout.addWidget(self.pushButton_delete)
        self.pushButton_sort = QtWidgets.QPushButton(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.pushButton_sort.setFont(font)
        self.pushButton_sort.setObjectName("pushButton_sort")
        self.pushButton_sort.clicked.connect(self.sort_item)
        self.verticalLayout.addWidget(self.pushButton_sort)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def add_item(self):
        row = self.listWidget.currentRow()  # 从列表小组件获取当前行
        title = '添加内容'  # 添加标题

        data, ok = QInputDialog.getText(self, title, title)

        if data and ok is not None:
            db.execute_sql(f"insert into listwidget (language1) values({data})")
            print(data)
            self.listWidget.insertItem(row, data)


    def edit_item(self):
        """        row = self.listWidget.currentRow()
        item=self.listWidget.item(row)
        这两句可以换为下面一句
        """
        item = self.listWidget.currentItem()
        if item is not None:
            title = '编辑内容'
            data, ok = QInputDialog.getText(self, title, title, QLineEdit.EchoMode.Normal, item.text())
            if data and ok is not None:
                item.setText(data)
        else:
           pass

    def delete_item(self):
        row = self.listWidget.currentRow()
        item = self.listWidget.item(row)
        title = '删除内容'  # 添加标题

        if item is None:
            return
        reply =QMessageBox.question(self, title,'确定删除此条记录？', QMessageBox.StandardButton.Yes|QMessageBox.StandardButton.No)

        if reply == QMessageBox.StandardButton.Yes:
            self.listWidget.takeItem(row)

    def sort_item(self):
        self.listWidget.sortItems()


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_add.setText(_translate("Dialog", "添加"))
        self.pushButton_edit.setText(_translate("Dialog", "编辑"))
        self.pushButton_delete.setText(_translate("Dialog", "移除"))
        self.pushButton_sort.setText(_translate("Dialog", "排序"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
